### ISSUE TITLE
feat: Support selection

### ISSUE THREAD

**Issue by kgpayne** [radbrt/tap-sharepointsites#3]
This is a great Tap @radbrt 🙌 Re: our discussion in Office Hours, you might like to support [selection]() of `List` streams as an alternative to storing named lists in config. I am not 100% familiar with Sharepoint Sites, but it appears the API supports [getting all the Lists on a Site](https://learn.microsoft.com/en-us/graph/api/list-list?view=graph-rest-1.0&tabs=http). So it should be possible to return all available lists from `discover_streams` [here](https://github.com/radbrt/tap-sharepointsites/blob/main/tap_sharepointsites/tap.py#L44) via a custom `Client` class (or just the `requests` library if the API is simple). e.g.

```python
from .client import SharepointSitesClient

def discover_streams(...):
    client = SharepointSitesClient(url=self.config["url"], client_id=self.config.get("client_id"))
    available_lists = client.get_all_lists() # uses the API to list all Lists for the given Site url
    return [ListStream(tap=self, name=list_name, path = f"lists/{ list_name }/items?expand=fields") for list_name in available_lists]
```

Then, using the `select` [extra](https://docs.meltano.com/concepts/plugins#select-extra) in config, you would be able to filter the discovered Lists using select patterns as follows:

```yaml
extractors:
- name: tap-sharepointsites
  config:
    api_url: "https://graph.microsoft.com/v1.0/sites/my-tenant.com:/sites/my-site:/"
    client_id: "fehui3rhui3443-f43fn43uf34-v42f24f43f2-f2f432f4f2"
  select:
  - my_first_list.*
  - my_second_list.*
```

The ".*" after the list names denotes "select all properties from stream 'my_first_list'". The SDK automagically filters returned records if a subset of properties is selected 🚀
